// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // USE_TEST_DB=1 переключает миграции и seed на тестовую базу,
    // чтобы `npm run db:test:reset` не трогал базу разработки
    url:
      process.env["USE_TEST_DB"] === "1"
        ? process.env["DATABASE_URL_TEST"]
        : process.env["DATABASE_URL"],
  },
});
